project:
  type: website

website:
  title: "Charles Lehnen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - photos.qmd
  favicon: "images/favicon-32x32.png"
  page-footer:
    right: "*Website design and workflow adapted from [Albury Catalina](https://github.com/alburycatalina/alburycatalina.github.io).*"
    

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

